export const narratorTypes = {
    FETCH_NARRATORS_REQUEST : 'FETCH_NARRATORS_REQUEST',
    FETCH_NARRATORS_ASYNC : 'FETCH_NARRATORS_ASYNC',
    FETCH_NARRATORS_SUCCESS : 'FETCH_NARRATORS_SUCCESS',
    FETCH_NARRATORS_FAILURE : 'FETCH_NARRATORS_FAILURE' 
}
