export const favouritesActionTypes = {
    ////OLD
    ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',
    REMOVE_FROM_FAVOURITES: 'REMOVE_FROM_FAVOURITES',
    ////NEW
    ADD_TO_FAVOURITES_REQUEST: 'ADD_TO_FAVOURITES_REQUEST',    
    ADD_TO_FAVOURITES_SUCCESS: 'ADD_TO_FAVOURITES_SUCCESS',
    ADD_TO_FAVOURITES_FAILURE: 'ADD_TO_FAVOURITES_FAILURE',
    REMOVE_FROM_FAVOURITES_REQUEST: 'REMOVE_FROM_FAVOURITES_REQUEST',    
    REMOVE_FROM_FAVOURITES_SUCCESS: 'REMOVE_FROM_FAVOURITES_SUCCESS',
    REMOVE_FROM_FAVOURITES_FAILURE: 'REMOVE_FROM_FAVOURITES_FAILURE',
    FETCH_FAVOURITES_REQUEST: 'FETCH_FAVOURITES_REQUEST',
    FETCH_FAVOURITES_SUCCESS: 'FETCH_FAVOURITES_SUCCESS',
    FETCH_FAVOURITES_FAILURE: 'FETCH_FAVOURITES_FAILURE'
}