export const playsandvotesActionTypes = {
    ADD_TO_VOTED: 'ADD_TO_VOTED',
    ADD_TO_VOTED_SUCCESS: 'ADD_TO_VOTED_SUCCESS',
    ADD_TO_VOTED_FAILURE: 'ADD_TO_VOTED_FAILURE',
    // REMOVE_FROM_VOTED: 'REMOVE_FROM_VOTED',
    ADD_TO_VOTED_REQUEST: 'ADD_TO_VOTED_REQUEST',
    
    ADD_TO_PLAYED: 'ADD_TO_PLAYED',
    ADD_TO_PLAYED_SUCCESS: 'ADD_TO_PLAYED_SUCCESS',
    ADD_TO_PLAYED_FAILURE: 'ADD_TO_PLAYED_FAILURE',
    ADD_TO_PLAYED_REQUEST: 'ADD_TO_PLAYED_REQUEST',     
}