export const playlistsActionTypes = {
    FETCH_PLAYLISTS_REQUEST: 'FETCH_PLAYLISTS_REQUEST',
    FETCH_PLAYLISTS_SUCCESS: 'FETCH_PLAYLISTS_SUCCESS',
    FETCH_PLAYLISTS_FAILURE: 'FETCH_PLAYLISTS_FAILURE'
}