export const audioplayingActionTypes = {
    SET_AUDIO_PLAYING_COMPLETE: 'SET_AUDIO_PLAYING_COMPLETE',
    SET_AUDIO_PLAYING_JUSTPLAY: 'SET_AUDIO_PLAYING_JUSTPLAY',
    SET_AUDIO_TRACKING: 'SET_AUDIO_TRACKING',
    SET_AUDIO_PAUSED: 'SET_AUDIO_PAUSED',
    SET_AUDIO_STOPED: 'SET_AUDIO_STOPED',
    SET_DEFAULT_AUDIO_VALUES_REQUEST: 'SET_DEFAULT_AUDIO_VALUES_REQUEST',
    SET_DEFAULT_AUDIO_VALUES_SUCCESS: 'SET_DEFAULT_AUDIO_VALUES_SUCCESS',
    SET_DEFAULT_AUDIO_VALUES_FAILURE: 'SET_DEFAULT_AUDIO_VALUES_FAILURE'

}
